trigger:
  branches:
    include:
      - main
      - feat/*
  paths:
    exclude:
      - 'infrastructure/*'
      - 'ami/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from '/' root folder."