---
AWSTemplateFormatVersion: '2010-09-09'
Description: "ZA - SBCPP - ALB stack"

Parameters:
  StackCore:
    Description: Name of core stack to import values from
    Type: String
  StackVPC:
    Description: Name of VPC stack to import values from
    Type: String
  StackSG:
    Description: Name of Security Group stack to import values from
    Type: String
  StackS3:
    Description: Name of S3 stack to import values from
    Type: String
  StackSNS:
    Description: Name of SNS stack to import values from
    Type: String
  CertificateArn:
    Description: ARN of certificate in ACM
    Type: String

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Shared"
        Parameters: 
          - StackCore
          - StackVPC
          - StackSG
          - StackS3
          - StackSNS
      - 
        Label: 
          default: "Local"
        Parameters: 
          - CertificateArn

Resources: 
  ALBWeb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: 
            Fn::ImportValue: !Sub "${StackS3}-S3BucketLogsName"
        - Key: idle_timeout.timeout_seconds
          Value: '120'
      SecurityGroups:
        - Fn::ImportValue: !Sub "${StackSG}-SecGroupWebAlb"
      Subnets:
        - Fn::ImportValue: !Sub "${StackVPC}-SubnetPublic1"
        - Fn::ImportValue: !Sub "${StackVPC}-SubnetPublic2"
        - Fn::ImportValue: !Sub "${StackVPC}-SubnetPublic3"
      Tags:
        - Key: Name
          Value: !Join
          - '-'
          - - Fn::ImportValue: !Sub "${StackCore}-ProjectUpper"
            - Fn::ImportValue: !Sub "${StackCore}-EnvironmentUpper"
            - "ALB"
            - "Web"
        - Key: Environment
          Value: 
            Fn::ImportValue: !Sub "${StackCore}-EnvironmentUpper"
        - Key: Project
          Value: 
            Fn::ImportValue: !Sub "${StackCore}-ProjectUpper"
        - Key: Role
          Value: Web
      Type: application

  TargetGroupWeb80:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      HealthCheckPath: "/"
      VpcId:
        Fn::ImportValue: !Sub "${StackVPC}-VPC"
      HealthCheckIntervalSeconds: 20
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 10

  ALBWebListener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupWeb80
      LoadBalancerArn: !Ref ALBWeb
      Port: 80
      Protocol: HTTP

  ALBWebListener443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupWeb80
      LoadBalancerArn: !Ref ALBWeb
      Port: 443
      Protocol: HTTPS

  CWAALBWebUnHealthyHostCount:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: True
      AlarmActions:
        - Fn::ImportValue: !Sub "${StackSNS}-SNSTopicCritical"
      AlarmDescription: UnHealthyHostCount
      AlarmName: !Join
          - '-'
          - - Fn::ImportValue: !Sub "${StackCore}-ProjectUpper"
            - Fn::ImportValue: !Sub "${StackCore}-EnvironmentUpper"
            - "ALB"
            - "Web"
            - "UnHealthyHostCount"
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TargetGroup
          Value: !GetAtt TargetGroupWeb80.TargetGroupFullName
        - Name: LoadBalancer
          Value: !GetAtt ALBWeb.LoadBalancerFullName
      EvaluationPeriods: 3
      InsufficientDataActions:
        - Fn::ImportValue: !Sub "${StackSNS}-SNSTopicCritical"
      MetricName: UnHealthyHostCount
      Namespace: AWS/ApplicationELB
      OKActions:
        - Fn::ImportValue: !Sub "${StackSNS}-SNSTopicCritical"
      Period: 60
      Statistic: Maximum
      Threshold: 0
      Unit: Count

Outputs:
  TargetGroupWeb80:
    Description: Target Group for Web Servers on port 80
    Value: !Ref TargetGroupWeb80
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroupWeb80"
  ALBWebArn:
    Description: Arn of Web ALB
    Value: !Ref ALBWeb
    Export:
      Name: !Sub "${AWS::StackName}-ALBWebArn"
  ALBWebDNS:
    Description: DNS name of Web ALB
    Value: !GetAtt ALBWeb.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-ALBWebDNS"